use crate::ckled2001::driver::CkLed;
use crate::ckled2001::led_address::*;

pub const LED_LAYOUT: &[CkLed] = &[
    // Row 0 (first block)
    CkLed { driver: 0, r: I_1,  g: G_1,  b: H_1  },
    CkLed { driver: 0, r: I_2,  g: G_2,  b: H_2  },
    CkLed { driver: 0, r: I_3,  g: G_3,  b: H_3  },
    CkLed { driver: 0, r: I_4,  g: G_4,  b: H_4  },
    CkLed { driver: 0, r: I_5,  g: G_5,  b: H_5  },
    CkLed { driver: 0, r: I_6,  g: G_6,  b: H_6  },
    CkLed { driver: 0, r: I_7,  g: G_7,  b: H_7  },
    CkLed { driver: 0, r: I_8,  g: G_8,  b: H_8  },
    CkLed { driver: 0, r: I_9,  g: G_9,  b: H_9  },
    CkLed { driver: 0, r: I_10, g: G_10, b: H_10 },
    CkLed { driver: 0, r: I_11, g: G_11, b: H_11 },
    CkLed { driver: 0, r: I_12, g: G_12, b: H_12 },
    CkLed { driver: 0, r: I_13, g: G_13, b: H_13 },
    CkLed { driver: 0, r: I_14, g: G_14, b: H_14 },
    CkLed { driver: 0, r: I_16, g: G_16, b: H_16 },

    // Row 1 (second block)
    CkLed { driver: 0, r: C_1,  g: A_1,  b: B_1  },
    CkLed { driver: 0, r: C_2,  g: A_2,  b: B_2  },
    CkLed { driver: 0, r: C_3,  g: A_3,  b: B_3  },
    CkLed { driver: 0, r: C_4,  g: A_4,  b: B_4  },
    CkLed { driver: 0, r: C_5,  g: A_5,  b: B_5  },
    CkLed { driver: 0, r: C_6,  g: A_6,  b: B_6  },
    CkLed { driver: 0, r: C_7,  g: A_7,  b: B_7  },
    CkLed { driver: 0, r: C_8,  g: A_8,  b: B_8  },
    CkLed { driver: 0, r: C_9,  g: A_9,  b: B_9  },
    CkLed { driver: 0, r: C_10, g: A_10, b: B_10 },
    CkLed { driver: 0, r: C_11, g: A_11, b: B_11 },
    CkLed { driver: 0, r: C_12, g: A_12, b: B_12 },
    CkLed { driver: 0, r: C_13, g: A_13, b: B_13 },
    CkLed { driver: 0, r: C_14, g: A_14, b: B_14 },
    CkLed { driver: 0, r: C_16, g: A_16, b: B_16 },

    // Row 2 (third block)
    CkLed { driver: 0, r: F_1,  g: D_1,  b: E_1  },
    CkLed { driver: 0, r: F_2,  g: D_2,  b: E_2  },
    CkLed { driver: 0, r: F_3,  g: D_3,  b: E_3  },
    CkLed { driver: 0, r: F_4,  g: D_4,  b: E_4  },
    CkLed { driver: 0, r: F_5,  g: D_5,  b: E_5  },
    CkLed { driver: 0, r: F_6,  g: D_6,  b: E_6  },
    CkLed { driver: 0, r: F_7,  g: D_7,  b: E_7  },
    CkLed { driver: 0, r: F_8,  g: D_8,  b: E_8  },
    CkLed { driver: 0, r: F_9,  g: D_9,  b: E_9  },
    CkLed { driver: 0, r: F_10, g: D_10, b: E_10 },
    CkLed { driver: 0, r: F_11, g: D_11, b: E_11 },
    CkLed { driver: 0, r: F_12, g: D_12, b: E_12 },
    CkLed { driver: 0, r: F_13, g: D_13, b: E_13 },
    CkLed { driver: 0, r: F_14, g: D_14, b: E_14 },
    CkLed { driver: 0, r: F_16, g: D_16, b: E_16 },

    // Driver 1 (fourth block)
    CkLed { driver: 1, r: C_16, g: A_16, b: B_16 },
    CkLed { driver: 1, r: C_15, g: A_15, b: B_15 },
    CkLed { driver: 1, r: C_14, g: A_14, b: B_14 },
    CkLed { driver: 1, r: C_13, g: A_13, b: B_13 },
    CkLed { driver: 1, r: C_12, g: A_12, b: B_12 },
    CkLed { driver: 1, r: C_11, g: A_11, b: B_11 },
    CkLed { driver: 1, r: C_10, g: A_10, b: B_10 },
    CkLed { driver: 1, r: C_9,  g: A_9,  b: B_9  },
    CkLed { driver: 1, r: C_8,  g: A_8,  b: B_8  },
    CkLed { driver: 1, r: C_7,  g: A_7,  b: B_7  },
    CkLed { driver: 1, r: C_6,  g: A_6,  b: B_6  },
    CkLed { driver: 1, r: C_5,  g: A_5,  b: B_5  },
    CkLed { driver: 1, r: C_3,  g: A_3,  b: B_3  },
    CkLed { driver: 1, r: C_1,  g: A_1,  b: B_1  },

    // Driver 1 (fifth block)
    CkLed { driver: 1, r: I_16, g: G_16, b: H_16 },
    CkLed { driver: 1, r: I_15, g: G_15, b: H_15 },
    CkLed { driver: 1, r: I_14, g: G_14, b: H_14 },
    CkLed { driver: 1, r: I_13, g: G_13, b: H_13 },
    CkLed { driver: 1, r: I_12, g: G_12, b: H_12 },
    CkLed { driver: 1, r: I_11, g: G_11, b: H_11 },
    CkLed { driver: 1, r: I_10, g: G_10, b: H_10 },
    CkLed { driver: 1, r: I_9,  g: G_9,  b: H_9  },
    CkLed { driver: 1, r: I_8,  g: G_8,  b: H_8  },
    CkLed { driver: 1, r: I_7,  g: G_7,  b: H_7  },
    CkLed { driver: 1, r: I_6,  g: G_6,  b: H_6  },
    CkLed { driver: 1, r: I_5,  g: G_5,  b: H_5  },
    CkLed { driver: 1, r: I_3,  g: G_3,  b: H_3  },
    CkLed { driver: 1, r: I_2,  g: G_2,  b: H_2  },

    // Driver 1 (sixth block)
    CkLed { driver: 1, r: F_16, g: D_16, b: E_16 },
    CkLed { driver: 1, r: F_15, g: D_15, b: E_15 },
    CkLed { driver: 1, r: F_14, g: D_14, b: E_14 },
    CkLed { driver: 1, r: F_10, g: D_10, b: E_10 },
    CkLed { driver: 1, r: F_6,  g: D_6,  b: E_6  },
    CkLed { driver: 1, r: F_5,  g: D_5,  b: E_5  },
    CkLed { driver: 1, r: F_4,  g: D_4,  b: E_4  },
    CkLed { driver: 1, r: F_3,  g: D_3,  b: E_3  },
    CkLed { driver: 1, r: F_2,  g: D_2,  b: E_2  },
    CkLed { driver: 1, r: F_1,  g: D_1,  b: E_1  },
];
